name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo engine
        run: sudo apt update && sudo apt install -y hugo unzip python3-pip

      - name: Install Aws CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
          cd /tmp
          unzip awscliv2.zip
          sudo ./aws/install --update
          cd -

      - name: Install awscli_plugin_endpoint
        run: pip3 install awscli_plugin_endpoint && pip3 show awscli_plugin_endpoint

      - name: copy ScaleWay AWS CLI configuration
        run: |
          mkdir ~/.aws
          cp ./aws/config ~/.aws/config

      - name: Compile items
        run: hugo -D

      - name: Push to Scaleway storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: /usr/local/bin/aws s3 sync --delete ./public/ s3://docs.petreguyennot.fr/